### ISSUE TITLE
Unable to download this as a zip-file (due to file name?)

### ISSUE THREAD

**Issue by AlexanderJulianErhard** [Geniuswas/Anno-2205-Revolutions-Mod-English#4]
Because this file is named 1.0.7z, when I try to download this file, due to the ending, my PC thinks this is a "7z" file, and I´m unable to successfully tell my PC this is supposed to be a zip file.
Even if I manually change the name to 1.0.7.zip (or 1.0.zip), it just creates an empty zip from which I can´t extract anything

**Comment by JamieRCHI** [comment]
It is Not a zip file. It is a 7zip file.
You need to install 7zip to extract the files.
